# Site settings
title: Pizza de Dados
description: O primeiro podcast sobre ciência de dados no Brasil
baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://pizzadedados.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pizza de Dados
user_description: O primeiro podcast sobre ciência de dados no Brasil
user_title: Pizza de Dados
email: pizzadedados@gmail.com
twitter_username: pizzadedados
facebook: pizzadedados
youtube: pizzadedados
instagram: pizzadedados
github_username:  pizzadedados
#gplus_username:  
logo_path: assets/img/signo.png

# Pizzaiolos photos
lele_photo: "https://i.imgur.com/nXuylsx.jpg"
jess_photo: "https://pbs.twimg.com/profile_images/950517230038548480/3LLLh6G5_400x400.jpg"
gust_photo: "https://pbs.twimg.com/profile_images/1072503866695041025/YEWcfLoh_400x400.jpg"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
plugins_dir:
  - jekyll-redirect-from
