# Site settings
title: Philipp's webpage
description: Philipp's webpage
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Philipp Nguyen
user_description: Hi, my name is Philipp. This page is still under construction, thank you for your patience!
user_title: PhD Student
email: philipp.nguyen@manchester.ac.uk
twitter_username: philippMUC
github_username:  PhilippNguyen
gplus_username:  lorem_ipsum
# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
