# Site settings
title: Philipp's webpage
description: Philipp's webpage
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Philipp Nguyen
user_description: Thank you for visiting my website! My name is Philipp. I am a PhD student in Aerospace Engineering at the University of Manchester, UK. Originally, I am from Kassel, right in the heart of Germany. I graduated with Master degrees in Aerospace Engineering and Management from the Technical University of Munich (TUM). This page is still under construction, thank you for your patience!
user_title: PhD Student
email: philipp.nguyen@manchester.ac.uk
twitter_username: philippMUC
github_username:  PhilippNguyen
gplus_username:  lorem_ipsum
# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
