# Site settings
title: alakarte
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/alakarte" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: alakarte
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Ca castagne !

company: 
  twitter: alakarteio
  github: alakarteio
  linkedin: alakarteio
  email: contact@alakarte.io

members:
  - fabien:
    color: purple
    firstname: fabien
    lastname: juif
    title: Co-Founder, Web Developer
    description: JE SUIS FABIEN !
    twitter: fabienjuif
    github: fabienjuif
    linkedin: fabienjuif
    email: fabien.juif@alakarte.io
    picture: "https://secure.gravatar.com/avatar/5e688e29837dd60ffc5d497b915ee5f3?s=500"
  - guillaume:
    color: blue
    firstname: guillaume
    lastname: crespel
    title: Co-Founder, Web Developer
    description: JE SUIS Guillaume !
    twitter: guilaumcrespel
    github: guillaumecrespel
    linkedin: guillaumecrespel
    email: guillaume.crespel@alakarte.io
    picture: "https://secure.gravatar.com/avatar/5e688e29837dd60ffc5d497b915ee5f3?s=500"


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
