# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet

# User settings
username: Anon Developer
user_description: Anon Developer
user_title: Software Developer
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum


# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
