# Site settings
title: 禽兽云
description: 禽兽云网址发布页！
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://qsyssrcom.github.io/particle/" # the base hostname & protocol for your site e.g. https://qsyssrcom.github.io/particle/

# User settings
username: 禽兽 养鸡场地址发布页
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Software Developer
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-cayman
