# Site settings
title: A blog about SUPER JOURNEY
description: A blog about SUPER JOURNEY
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "superpiggenius.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: SUPERPIGGENIUS
user_description: BEGGINER LEVEL DEVELOPER
user_title: Web Developer
email: piggenius33@gmail.com  
twitter_username: superpiggenius
github_username:  superpiggenius
gplus_username:  none

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
