# Site settings
title: Cambrian-Node.net
description: Codes and Games
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cambrian-Node
user_description: Idk, I make games.
user_title: Software Developer
email: contact@cambrian-node.net
github_username:  cambriannode

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
