# Site settings
title: Pizza de Dados
description: O primeiro podcast sobre ciência de dados no Brasil
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 
user_description: O primeiro podcast sobre ciência de dados no Brasil
user_title: Pizza de Dados
email: pizzadedados@gmail.com
twitter_username: pizzadedados
facebook: pizzadedados
youtube: pizzadedados
instagram: pizzadedados
github_username:  pizzadedados
#gplus_username:  
logo_path: assets/img/signo.png

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
plugins_dir:
  - jekyll-redirect-from
